### LISTA DE USUARIOS
GET http://127.0.0.1:4000/api/usuarios
Accept: application/json
Content-Type: application/json

### CREAR NUEVO USUARIO
POST http://127.0.0.1:4000/api/usuarios
Accept: application/json
Content-Type: application/json

{
    "username":"Luis"
}

### ELIMINAR USUARIO
DELETE http://127.0.0.1:4000/api/usuarios/65c4f4fe15f5f4843262d5f4
Accept: application/json
Content-Type: application/json